//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class 使用優惠明細UsingCouponLists
    {
        public int 使用優惠明細UsingID { get; set; }
        public int 優惠明細編號CouponList_ID { get; set; }
        public int 訂單編號Order_ID { get; set; }
    
        public virtual 訂單總表Orders 訂單總表Orders { get; set; }
        public virtual 優惠明細CouponLists 優惠明細CouponLists { get; set; }
    }
}
